source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target ‘Arqami DineIn’ do
pod 'Kingfisher', '~> 3.0'
pod "JDropDownAlert"
pod 'RealmSwift'
pod 'IQKeyboardManagerSwift', '5.0.0'
pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
end
