# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

project 'Offarat.xcodeproj'

target 'Offarat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Offarat
  pod 'AccordionSwift', '~> 2.0.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  
end
